# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "async-timeout" = super.buildPythonPackage rec {
    pname = "async-timeout";
    version = "5.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fe/ba/e2081de779ca30d473f21f5b30e0e737c438205440784c7dfc81efc2b029/async_timeout-5.0.1-py3-none-any.whl";
      sha256 = "0v77gzkjk90zg9d41jfap9j86v09bssrh8zcax2kb1gzcsaq1qrr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2025.8.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e5/48/1549795ba7742c948d2ad169c1c8cdbae65bc450d6cd753d124b17c8cd32/certifi-2025.8.3-py3-none-any.whl";
      sha256 = "198pyad6jy7x5wx5v3ln8ik5vijhjfprb19jzyi6pc5iry9j9hgn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "3.4.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/83/2d/5fd176ceb9b2fc619e63405525573493ca23441330fcdaee6bef9460e924/charset_normalizer-3.4.3.tar.gz";
      sha256 = "054d0r8rimd5wrcph6p7p2dblcni614llpa6f75nykr4022lpkkg";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "docker" = super.buildPythonPackage rec {
    pname = "docker";
    version = "7.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e3/26/57c6fb270950d476074c087527a558ccb6f4436657314bfb6cdf484114c4/docker-7.1.0-py3-none-any.whl";
      sha256 = "1h2zin4z2dsvm3l6l4q39yyxi8r2fjwcynrjgpkzjim7y2vr6sy9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."requests"
      self."urllib3"
    ];
  };
  "exceptiongroup" = super.buildPythonPackage rec {
    pname = "exceptiongroup";
    version = "1.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/f4/c6e662dade71f56cd2f3735141b265c3c79293c109549c1e6933b0651ffc/exceptiongroup-1.3.0-py3-none-any.whl";
      sha256 = "044alxyhkfdlr5z3xlpnf5lv78310bnsgnkdmm669l0k1ip1w4ad";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."typing-extensions"
    ];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "3.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/76/c6/c88e154df9c4e1a2a66ccf0005a88dfb2650c1dffb6f5ce603dfbd452ce3/idna-3.10-py3-none-any.whl";
      sha256 = "1lw72a5swas501zvkpd6dsryj5hzjijqxs3526kbp7151md1jvcl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "iniconfig" = super.buildPythonPackage rec {
    pname = "iniconfig";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2c/e1/e6716421ea10d38022b952c159d5161ca1193197fb744506875fbb87ea7b/iniconfig-2.1.0-py3-none-any.whl";
      sha256 = "0q5piqbflf6jz0zd67lvmfzlrj9m96zwd0am8dvhwf0j6drabswx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "neo4j" = super.buildPythonPackage rec {
    pname = "neo4j";
    version = "5.28.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/00/1f74089c06aec1fac9390e2300a6a6b2381e0dac281783d64ccca9d681fd/neo4j-5.28.2-py3-none-any.whl";
      sha256 = "150sm693nlq0v9kbfw8ycmd17mrqma8l6wn943lygpp6xv1valsw";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytz"
    ];
  };
  "numpy" = super.buildPythonPackage rec {
    pname = "numpy";
    version = "2.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a9/75/10dd1f8116a8b796cb2c737b674e02d02e80454bda953fa7e65d8c12b016/numpy-2.0.2.tar.gz";
      sha256 = "0y3fcd268cnrc8ipcmj1c082an4j4a4wj3dbcjlf500qxryrhg48";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "25.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/20/12/38679034af332785aac8774540895e234f4d07f7545804097de4b666afd8/packaging-25.0-py3-none-any.whl";
      sha256 = "1154669ydc149dash6yaf3n2byqiqvajf8isdc282xgin7r2wmr9";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pluggy" = super.buildPythonPackage rec {
    pname = "pluggy";
    version = "1.6.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/54/20/4d324d65cc6d9205fabedc306948156824eb9f0ee1633355a8f7ec5c66bf/pluggy-1.6.0-py3-none-any.whl";
      sha256 = "0ij7vmsc72c3bnaf78r77g1k5jcldmbca2vw6zlrac41srnjf879";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pygments" = super.buildPythonPackage rec {
    pname = "pygments";
    version = "2.19.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c7/21/705964c7812476f378728bdf590ca4b771ec72385c533964653c68e86bdc/pygments-2.19.2-py3-none-any.whl";
      sha256 = "02zcwmz07fgc2wb7968yhm4n9wjgccl3kg243nw8nn1xq2306m46";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytest" = super.buildPythonPackage rec {
    pname = "pytest";
    version = "8.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a8/a4/20da314d277121d6534b3a980b29035dcd51e6744bd79075a6ce8fa4eb8d/pytest-8.4.2-py3-none-any.whl";
      sha256 = "0y9f4yzjzrn5qc5k5afg8yjrfd0cf74kj6x1i3f5nfpwwc6qhbw7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."exceptiongroup"
      self."iniconfig"
      self."packaging"
      self."pluggy"
      self."pygments"
      self."tomli"
    ];
  };
  "pytest-snapshot" = super.buildPythonPackage rec {
    pname = "pytest-snapshot";
    version = "0.9.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cb/29/518f32faf6edad9f56d6e0107217f7de6b79f297a47170414a2bd4be7f01/pytest_snapshot-0.9.0-py3-none-any.whl";
      sha256 = "1aylnfln4sb7vpcw3xg38s4wihbbsf232kjyahxfb3w63k1f37sb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pytest"
    ];
  };
  "python-dotenv" = super.buildPythonPackage rec {
    pname = "python-dotenv";
    version = "1.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5f/ed/539768cf28c661b5b068d66d96a2f155c4971a5d55684a514c1a0e0dec2f/python_dotenv-1.1.1-py3-none-any.whl";
      sha256 = "1p141r6qwi0cjcvpjwz79qi02zj9p9wmq7syyn7zh0i6zr23dwii";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pytz" = super.buildPythonPackage rec {
    pname = "pytz";
    version = "2025.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/81/c4/34e93fe5f5429d7570ec1fa436f1986fb1f00c3e0f43a589fe2bbcd22c3f/pytz-2025.2-py2.py3-none-any.whl";
      sha256 = "001gxkq46b96nzhdwymxzgvcng4g90snyjwgxck4ri6qdllpdpsx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "redis" = super.buildPythonPackage rec {
    pname = "redis";
    version = "6.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/02/89e2ed7e85db6c93dfa9e8f691c5087df4e3551ab39081a4d7c6d1f90e05/redis-6.4.0-py3-none-any.whl";
      sha256 = "0zwb4kfqh2kn18rjlbymcnqp83w3skki8j6z9i3fjr22c2llym7h";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."async-timeout"
    ];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.32.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/1e/db/4254e3eabe8020b458f1a747140d32277ec7a271daf1d235b70dc0b4e6e3/requests-2.32.5-py3-none-any.whl";
      sha256 = "1dpz38b6lnn8fcad7kfiagagbc3djy3f35a24qrdakx36x3gjqi4";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."charset-normalizer"
      self."idna"
      self."urllib3"
    ];
  };
  "testcontainers" = super.buildPythonPackage rec {
    pname = "testcontainers";
    version = "4.13.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/30/f0660686920e09680b8afb0d2738580223dbef087a9bd92f3f14163c2fa6/testcontainers-4.13.1-py3-none-any.whl";
      sha256 = "0lj9mx97d03p71p262jy4hycbwfn1643q5fc1cx6gfjy44x03rhh";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docker"
      self."python-dotenv"
      self."typing-extensions"
      self."urllib3"
      self."wrapt"
    ];
  };
  "testcontainers-core" = super.buildPythonPackage rec {
    pname = "testcontainers-core";
    version = "0.0.1rc1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a0/84/ac813e7aed7a527e5bc4c7cbb6e47d72498e76b8371e3805ccab96619b38/testcontainers_core-0.0.1rc1-py3-none-any.whl";
      sha256 = "1590wlby9p6nhgbjlds0xp65616vf0nb20b4q81jvb2jvcnvza39";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."docker"
      self."wrapt"
    ];
  };
  "testcontainers-neo4j" = super.buildPythonPackage rec {
    pname = "testcontainers-neo4j";
    version = "0.0.1rc1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/46/66/8d4c91ffc41ddf5f292d7b07331f59d5f6857d3b02f2b3c7419694ff02a4/testcontainers_neo4j-0.0.1rc1-py3-none-any.whl";
      sha256 = "0fg1v6hl6z7di9ysiayij3444cfi7806dh85hg0kjf4skns9s8w0";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."neo4j"
      self."testcontainers-core"
    ];
  };
  "testcontainers-redis" = super.buildPythonPackage rec {
    pname = "testcontainers-redis";
    version = "0.0.1rc1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0c/a2/34d6576c52c5916503ecd2f7991689b0272167457f13c36093a12fddfdab/testcontainers_redis-0.0.1rc1-py3-none-any.whl";
      sha256 = "02vibp4kc2285k37fkn0xsbks2cy1964v62rn3vd7fvlfihzqpnn";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."redis"
      self."testcontainers-core"
    ];
  };
  "tomli" = super.buildPythonPackage rec {
    pname = "tomli";
    version = "2.2.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/6e/c2/61d3e0f47e2b74ef40a68b9e6ad5984f6241a942f7cd3bbfbdbd03861ea9/tomli-2.2.1-py3-none-any.whl";
      sha256 = "1k45vj5659ghprcb5rvxlx3z3jdrcbvzkvpk1jfpf224bwycfmfb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.15.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/18/67/36e9267722cc04a6b9f15c7f3441c2363321a3ea07da7ae0c0707beb2a9c/typing_extensions-4.15.0-py3-none-any.whl";
      sha256 = "0j75qhcc0p627f464gd7kjcirdzcga5zl32a0w4ann2phk31kyph";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "2.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a7/c2/fe1e52489ae3122415c51f387e221dd0773709bad6c6cdaa599e8a2c5185/urllib3-2.5.0-py3-none-any.whl";
      sha256 = "1p7hrw2cc75zyqbb49diqi371gxkis07225mfkii6spsq1ridc76";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "wrapt" = super.buildPythonPackage rec {
    pname = "wrapt";
    version = "1.17.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/95/8f/aeb76c5b46e273670962298c23e7ddde79916cb74db802131d49a85e4b7d/wrapt-1.17.3.tar.gz";
      sha256 = "1l36lvxf02cfm8ypi34zdr3x6iifiqn2lzyixd7gw454xa7v0vpn";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
